### ISSUE TITLE
Provide VPN server name in Gatemon results

### ISSUE THREAD

**Issue by oliver** [FreifunkBremen/gatemon#18]
Since Gatemon now provides some performance measurements as well, it would be useful to also see which VPN server is used by each Gatemon instance, because the VPN server might affect the performance measurements of a Gatemon.

**Comment by ghost** [comment]
If you provide a shell snippet I'm willing to include the information. After some trying to get the information from the status page I have no idea how to gather the information.

**Comment by ghost** [comment]
Das ist fast ein Jahr alt. Wird da noch was kommen? Sonst mach ich das zu.

**Comment by ghost** [comment]
In dda9147c188c3127cce3cf80cfd8a49a5163c4f5 wird der erste HOP im MTR uebermittelt. Muss in gatemon-html noch angezeigt werden.

**Comment by oliver** [comment]
Mit https://github.com/FreifunkBremen/gatemon-html/commit/e9c1de8e29a1ada37e04b4ad4929c6d103e17a61 wird der Wert aus dem ersten Hop jetzt auf https://status.ffhb.de/ unten in der Gatemon-Liste angezeigt.
