### ISSUE TITLE
hostid is unusable at least on Debian

### ISSUE THREAD

**Issue by oliver** [FreifunkBremen/gatemon#2]
According to https://bugs.debian.org/595790 the `hostid` command under Debian will in many cases print "007f0101". So if we add more Raspian monitoring systems, we will probably get clashes between UUIDs.

Some suggestions:
- use `/var/lib/dbus/machine-id`, as suggested at http://0pointer.de/blog/projects/ids.html, with fallback to `hostid`
- use something like MAC address as basis for UUID
- require that some UUID is set manually in `/etc/check-all-vpn-exits.cfg`
- fail if `hostid` returns 007f0101, so that users are forced to set some hostid in `/etc/hostid`

**Comment by jplitza** [comment]
I would vote for either `/var/lib/dbus/machine-id` (would require DBus on the system) or for `/etc/machine-id` (would require systemd on the system). From `machine-id(5)`:

```
   The simple configuration file format of /etc/machine-id originates in
   the /var/lib/dbus/machine-id file introduced by D-Bus. In fact, this
   latter file might be a symlink to /etc/machine-id.
```

**Comment by ghost** [comment]
No. Works. I use debian, you know?!

**Comment by jplitza** [comment]
Doesn't work on standard configuration. From `gethostid(3)`:

```
NOTES
   In  the  glibc  implementation,  the  hostid  is  stored  in  the  file
   /etc/hostid.  (In glibc versions before 2.2, the  file  /var/adm/hostid
   was used.)

   In  the  glibc implementation, if gethostid() cannot open the file con‐
   taining the host ID, then it obtains the hostname using gethostname(2),
   passes  that  hostname  to  gethostbyname_r(3)  in  order to obtain the
   host's IPv4 address, and returns a value obtained by bit-twiddling  the
   IPv4 address.  (This value may not be unique.)
```

There is no `/etc/hostid` by default, and because Debian by default adds an entry `127.0.1.1 $hostname` to `/etc/hosts`, that procedure yields `007f0101` in default configuration.

So if it works for you, you probably have modified/removed that entry in `/etc/hosts`. But for example, vpn02 also gives

```
root@vpn02 ~ # hostid
007f0101
```

**Comment by ghost** [comment]
root@vpn01 ~ # hostid
10ac0300
root@vpn02 ~ # hostid
007f0101
root@vpn03 ~ # hostid
48259494
root@meshmon-2 ~ # hostid
10ac0300
root@meshmon-1 ~ # hostid
10ac0400
root@ff-10 ~ # hostid
66860a15
root@vpn06:~# hostid
75b903d6

**Comment by ghost** [comment]
ja. es KANN zu ueberschneidungen kommen, ist aber nicht der regelfall

**Comment by ghost** [comment]
dbus is no standardpackage

**Comment by ghost** [comment]
ip link | awk '/link\/ether/ { print $2 }' | head -n1 | tr -d ':'

**Comment by jplitza** [comment]
Doch, wie oben ausgeführt ist es der Regelfall im Sinne von Standardkonfiguration. Dass es auf deinen Systemen nicht vorkommt, weil du `/etc/hosts` immer anpasst, ist ja ein anderer Schnack. Aber willst du in die Readme von Meshmon schreiben, dass man den Eintrag in seiner `/etc/hosts` anpassen soll?

`ip link | awk '/link\/ether/ { print $2 }' | head -n1 | tr -d ':'` ist nicht stabil, sondern hängt von der Reihenfolge in der die Interfaces erkannt wurden ab. Wenn ich das Modul für mein eth0 (bei mir das erste) neu lade (kommt bei Rechnern mit r8168/r8169 tatsächlich vor, dass man da den Treiber wechseln will) wird das wieder hinten angestellt und andere Interfaces (wlan0, VPNs) rutschen nach oben. Auch der Austausch der Netzwerkkarte sollte denke ich nicht unbedingt zu einer neuen ID führen.

Was spricht denn gegen

``` bash
for file in /etc/machine-id /var/lib/dbus/machine-id /etc/hostid; do
  if [ -r "$file" ]; then
    HOSTID="$(<"$file")"
    break
  fi
done
if [ -z "$HOSTID" ]; then
  echo "Could not determine unique host ID."
  exit 1
fi
```

**Comment by ghost** [comment]
Feel free to implement (bitte so, dass wir keine STDERR-Meldungen bekommen)

**Comment by oliver** [comment]
Die Lösung von jpltza gefällt mir.

Sollten wir die Hostid danach noch auf max. 12 Zeichen oder so kürzen, damit das auf der Website nicht das Layout sprengt? Wobei, vllt. kürzen wir das lieber einfach auf der Website bei der Ausgabe.

**Comment by ghost** [comment]
Jup
