### ISSUE TITLE
avoid starting script on all hosts at the same time

### ISSUE THREAD

**Issue by oliver** [FreifunkBremen/gatemon#4]
It looks like the three meshmon clients we have at the moment all start their cronjob at the 10-minute mark (ie. the cronjob probably looks like `*/10 * * * * root /usr/local/bin/check-all-vpn-exits.sh` on all hosts). This might cause unexpected load spikes and unrealistic measurements at these times, esp. if more meshmon clients are set up.

Or is it useful to run all checks at the same time, to get a real snapshot of the whole network at nearly the same timestamp?

Anyway, possible solutions I could think of:
- add a random sleep of up to 10 minutes at the start of the script (if the uuid is used as random seed, the same sleep duration will always be used on the same host)
- instruct users to configure their cronjob with a randomly-picked minute offset
- provide an installer script (or DEB/RPM packages) for installation, and let installer set a random minute offset when creating cronjob

I'm leaning towards the first solution, but there would have to be a command line switch to disable this (for debugging). Also, the sleep would have to happen before the runfile is created or checked.

**Comment by ghost** [comment]
Do the random sleep stuff and pull request. Thanks

**Comment by ghost** [comment]
Closed with d8e65a44e8e7431999f879c21da0312dc5a3d584
