### ISSUE TITLE
include more information in JSON files

### ISSUE THREAD

**Issue by oliver** [FreifunkBremen/gatemon#6]
The JSON files generated by gatemon should include more information, eg.:
- duration of NTP/DNS/DHCP requests
- error messages from curl, if the uplink check fails

Esp. the IPv4 DHCP duration could be useful, since delayed DHCP answers are happening already in the FFHB network, and it might be useful to have harder data on that phenomenon.

I don't see an easy way to include this additional info with the current JSON schema.
I guess we need to change the JSON schema in a way that makes it incompatible with the current schema, which would probably also require changes in the Summarizer in gatemon-html; which again would probably mean that we have to update all gatemon clients at about the same time, or that we need a version info in the JSON file. But maybe I'm overthinking this again...

**Comment by oliver** [comment]
After discussion it has been decided to change the format even if it becomes incompatible.

So `"ntp":[{"ipv4":1,"ipv6":1}]` could become something like `"ntp":[{"ipv4": {"status":0, "time":123, "error":"received invalid NTP response"}, "ipv6": {"status":1, "time":123}}]`, allowing to specify time (in msec) and error message, and also allowing to add other fields in the future.

**Comment by ghost** [comment]
yep

**Comment by SimJoSt** [comment]
Has this issue been already solved or are there any plans to implement this in the future?

**Comment by oliver** [comment]
I don't think I'll get to this in the near future. But I still think it would be a useful feature, so that we get information not only for errors but also for general performance.

**Comment by ghost** [comment]
duration is implemented

**Comment by ghost** [comment]
Closed by 2bd32bf56867c4cf964727d0189ee0ed47ee0e16
